// Created by iWeb 3.0.2 local-build-20101024

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Home.utf8.it_files/Home.utf8.itMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id36');adjustFontSizeIfTooBig('id36');adjustLineHeightIfTooBig('id37');adjustFontSizeIfTooBig('id37');adjustLineHeightIfTooBig('id38');adjustFontSizeIfTooBig('id38');adjustLineHeightIfTooBig('id49');adjustFontSizeIfTooBig('id49');adjustLineHeightIfTooBig('id62');adjustFontSizeIfTooBig('id62');adjustLineHeightIfTooBig('id70');adjustFontSizeIfTooBig('id70');adjustLineHeightIfTooBig('id71');adjustFontSizeIfTooBig('id71');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id7');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id12');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id14');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id16');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id21');fixupIECSS3Opacity('id22');fixupIECSS3Opacity('id23');fixupIECSS3Opacity('id24');fixupIECSS3Opacity('id25');fixupIECSS3Opacity('id26');fixupIECSS3Opacity('id28');fixupIECSS3Opacity('id29');fixupIECSS3Opacity('id30');fixupIECSS3Opacity('id31');fixupIECSS3Opacity('id32');fixupIECSS3Opacity('id33');fixupIECSS3Opacity('id34');fixupIECSS3Opacity('id35');fixupIECSS3Opacity('id39');fixupIECSS3Opacity('id40');fixupIECSS3Opacity('id41');fixupIECSS3Opacity('id42');fixupIECSS3Opacity('id43');fixupIECSS3Opacity('id44');fixupIECSS3Opacity('id45');fixupIECSS3Opacity('id46');fixupIECSS3Opacity('id47');fixupIECSS3Opacity('id48');fixupIECSS3Opacity('id50');fixupIECSS3Opacity('id51');fixupIECSS3Opacity('id52');fixupIECSS3Opacity('id53');fixupIECSS3Opacity('id54');fixupIECSS3Opacity('id55');fixupIECSS3Opacity('id56');fixupIECSS3Opacity('id57');fixupIECSS3Opacity('id58');fixupIECSS3Opacity('id59');fixupIECSS3Opacity('id60');fixupIECSS3Opacity('id61');fixupIECSS3Opacity('id63');fixupIECSS3Opacity('id64');fixupIECSS3Opacity('id65');fixupIECSS3Opacity('id66');fixupIECSS3Opacity('id67');fixupIECSS3Opacity('id68');fixupIECSS3Opacity('id69');applyEffects()}
