title:              "lamafilm"
email:              "info@lamafilm.net" 
description:        "Lama film produzioni"
author:             lamafilm
baseurl:            "/"
url:                "http://www.lamafilm.net"
permalink: /:slug/
logo: "/images/cropped-scritture_logo-1.jpg"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           
paginate_path:      "/posts/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
  "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js", "bin/cbuild"]


lang:
    default: it
    posted_by: di
    previus_post: "articolo precedente"
    next_post: "aricolo successivo"
    previus: "precedente"
    next: "successivo"
    post: "articolo"
    all_posts: "tutti gli articoli"
    read: "leggi"
    enter_keywords: "cerca le parole"


menu:
  - 1:
     - name: "contatti"
     - link: "/contatti/"
#  - 2:
#     - name: "chi siamo"
#     - link: "/chi/"
     
collection:
  credits:
    output: true
    permalink: /credits/:path/